// Generated by CoffeeScript 2.3.1
(function() {
  // Generated automatically by nearley, version 2.15.1
  // http://github.com/Hardmath123/nearley
  (function() {
    /*======================================================================================================*/
    /* ====================================================================================================
    nearleyc sqlish.ne -o sqlish.coffee && coffee -c sqlish.coffee && nearley-test -q -i 'create field;' sqlish.js
    nearley-railroad sqlish.ne -o sqlish.html
    nearley-unparse -n 10 sqlish.js

    create layout #mylayout;
    set grid to G5;
    set debug to false;
    create field at A1;
    create field at A1..B2;
    create field #myfield at A1..B2;
    select fields #myfield:                       set top border to 'thin, blue';
    select fields #myfield, #thatone, .h, A1..B2: set top border to 'thin, blue';
    select fields .caption:                       set horizontal alignment to left;

     * in layout #mylayout, create field at A1;
     * in layout #mylayout, create field at A1..B2;
     * in layout #mylayout, create field at A1, at B2, #anotherfield at C3..D5;
     * in layout #mylayout, create field #myfield at A1..B2;
     * select layout #mylayout, then create: field  #myfield at A1, field at B1, field #another at C3;
     * select layout #mylayout, then create  field: #myfield at A1,       at B1,       #another at C3;
     * create layout: #this, #that;
     * create: layout #this, layout #that;
     * create layout #mylayout, then: create field  #caption.h at A1..D1, create field .text at: A2, B2, C2, D2;
     * create layout #mylayout, then create: field  #caption.h at A1..D1,        field .text at: A2, B2, C2, D2;
     * create layout #mylayout, then create  field: #caption.h at A1..D1,              .text at: A2, B2, C2, D2;

     */
    /*======================================================================================================*/
    var $cellkey, $clasz, $create_layout, $create_named_field, $create_unnamed_field, $filter, $first, $flatten, $id, $ignore, $rangekey, $select_fields, $set_debug, $set_grid, CND, _create_field, alert, badge, debug, echo, enumerate, filter, filtered, flatten, get_loc, grammar, help, id, info, join, jr, lexer, log, rpr, show, urge, warn, whisper, Σ;
    id = function(d) {
      return d[0];
    };
    'use strict';
    
    //###########################################################################################################
    CND = require('cnd');
    rpr = CND.rpr;
    badge = 'SQLISH/GRAMMAR';
    log = CND.get_logger('plain', badge);
    info = CND.get_logger('info', badge);
    whisper = CND.get_logger('whisper', badge);
    alert = CND.get_logger('alert', badge);
    debug = CND.get_logger('debug', badge);
    warn = CND.get_logger('warn', badge);
    help = CND.get_logger('help', badge);
    urge = CND.get_logger('urge', badge);
    echo = CND.echo.bind(CND);
    ({lexer} = require('./sqlish-lexer'));
    
    //-----------------------------------------------------------------------------------------------------------
    log = function(...P) {
      return console.log(...P);
    };
    jr = JSON.stringify;
    
    //-----------------------------------------------------------------------------------------------------------
    flatten = function(d, n = 1) {
      if (n < 1) {
        return d;
      }
      return (n === 1 ? d : flatten(d, n - 1)).reduce((function(a, b) {
        return a.concat(b);
      }), []);
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $flatten = function(d, n = 1) {
      return flatten(d, n);
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $filter = function(d) {
      return d.filter(function(x) {
        return x !== null;
      });
    };
    
    //-----------------------------------------------------------------------------------------------------------
    filter = function*(d) {
      var i, len, x;
      for (i = 0, len = d.length; i < len; i++) {
        x = d[i];
        if (x === null) {
          continue;
        }
        if (x === Symbol.for('LWS')) {
          continue;
        }
        if (x === Symbol.for('STOP')) {
          continue;
        }
        if (x.type === 'semicolon') {
          continue;
        }
        yield x;
      }
    };
    
    //-----------------------------------------------------------------------------------------------------------
    filtered = function(d) {
      return [...(filter(d))];
    };
    
    //-----------------------------------------------------------------------------------------------------------
    enumerate = function*(iterator) {
      var idx, results, x;
      idx = 0;
      results = [];
      for (x of iterator) {
        results.push((yield [x, idx++]));
      }
      return results;
    };
    
    //-----------------------------------------------------------------------------------------------------------
    show = function(ref, d) {
      var i, idx, len, token;
      for (idx = i = 0, len = d.length; i < len; idx = ++i) {
        token = d[idx];
        // log token
        log(CND.grey(ref), CND.white(idx), CND.yellow(jr(token)));
      }
      return null;
    };
    
    //-----------------------------------------------------------------------------------------------------------
    Σ = function(key) {
      return function() {
        return Symbol.for(key);
      };
    };
    $ignore = function() {
      return null;
    };
    join = function(x, joiner = '') {
      return x.join(joiner);
    };
    $first = function(x) {
      return x[0];
    };
    get_loc = function(token) {
      return `${token.line}#${token.col}`;
    };
    
    // #-----------------------------------------------------------------------------------------------------------
    // $float              = ( d, loc ) -> { type: 'float',      value: "#{d[ 0 ].join ''}.#{d[ 2 ].join ''}", }
    // $integer            = ( d, loc ) -> { type: 'integer',    value: ( d[ 0 ].join '' ),                    }

    //-----------------------------------------------------------------------------------------------------------
    $clasz = function(d) {
      var type;
      type = 'clasz';
      id = d[0].value;
      return {
        type: 'clasz',
        id
      };
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $id = function(d) {
      var type;
      type = 'id';
      id = d[0].value;
      return {
        type: 'id',
        id
      };
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $cellkey = function(d) {
      var colletters, rowdigits, type;
      type = 'cellkey';
      [colletters, rowdigits] = flatten(d, 1);
      colletters = colletters.value;
      rowdigits = rowdigits.value;
      return {type, colletters, rowdigits};
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $rangekey = function(d) {
      var _, first, second, type;
      type = 'rangekey';
      [first, _, second] = d;
      return {type, first, second};
    };
    
    //-----------------------------------------------------------------------------------------------------------
    _create_field = function(first, selector, id) {
      var loc, ref1, type;
      loc = get_loc(first);
      type = 'create_field';
      if (selector.type === 'star') {
        selector = {
          type: 'star'
        };
      }
      id = (ref1 = id != null ? id.id : void 0) != null ? ref1 : null;
      return {type, id, selector, loc};
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $create_named_field = function(d) {
      var AT, CREATE, FIELD, selector;
      [CREATE, FIELD, id, AT, selector] = filtered(d);
      return _create_field(CREATE, selector, id);
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $create_unnamed_field = function(d) {
      var AT, CREATE, FIELD, selector;
      [CREATE, FIELD, AT, selector] = filtered(d);
      return _create_field(CREATE, selector, null);
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $create_layout = function(d) {
      var CREATE, LAYOUT, STOP, _, loc, type;
      [CREATE, _, LAYOUT, _, id, _, STOP] = d;
      loc = get_loc(CREATE);
      type = 'create_layout';
      id = id.id;
      return {type, id, loc};
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $set_grid = function(d, loc) {
      var GRID, SET, STOP, TO, _, cellkey, size, type;
      [SET, _, GRID, _, TO, _, cellkey, _, STOP] = d;
      loc = get_loc(SET);
      type = 'set_grid';
      size = cellkey;
      return {type, size, loc};
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $set_debug = function(d, loc) {
      var DEBUG, SET, STOP, TO, _, toggle, type, value;
      [SET, _, DEBUG, _, TO, _, toggle, _, STOP] = d;
      loc = get_loc(SET);
      type = 'set_debug';
      value = toggle.value;
      return {type, value, loc};
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $select_fields = function(d) {
      var FIELDS, SELECT, loc, selectors, type;
      // debug '7744', filtered d
      [SELECT, FIELDS, selectors] = filtered(d);
      loc = get_loc(SELECT);
      type = 'select_fields';
      return {type, selectors, loc};
    };
    grammar = {
      Lexer: lexer,
      ParserRules: [
        {
          "name": "phrase",
          "symbols": ["create"],
          "postprocess": $first
        },
        {
          "name": "phrase",
          "symbols": ["set"],
          "postprocess": $first
        },
        {
          "name": "phrase",
          "symbols": ["select"],
          "postprocess": $first
        },
        {
          "name": "create",
          "symbols": ["create_field"],
          "postprocess": $first
        },
        {
          "name": "create",
          "symbols": ["create_layout"],
          "postprocess": $first
        },
        {
          "name": "create_field",
          "symbols": ["create_named_field"],
          "postprocess": $first
        },
        {
          "name": "create_field",
          "symbols": ["create_unnamed_field"],
          "postprocess": $first
        },
        {
          "name": "create_named_field",
          "symbols": [
            {
              "literal": "create"
            },
            "__",
            {
              "literal": "field"
            },
            "__",
            "id",
            "__",
            {
              "literal": "at"
            },
            "__",
            "cell_selector",
            "_",
            "stop"
          ],
          "postprocess": $create_named_field
        },
        {
          "name": "create_unnamed_field",
          "symbols": [
            {
              "literal": "create"
            },
            "__",
            {
              "literal": "field"
            },
            "__",
            {
              "literal": "at"
            },
            "__",
            "cell_selector",
            "_",
            "stop"
          ],
          "postprocess": $create_unnamed_field
        },
        {
          "name": "create_layout",
          "symbols": ["create_named_layout"],
          "postprocess": $first
        },
        {
          "name": "create_named_layout",
          "symbols": [
            {
              "literal": "create"
            },
            "__",
            {
              "literal": "layout"
            },
            "__",
            "id",
            "_",
            "stop"
          ],
          "postprocess": $create_layout
        },
        {
          "name": "set",
          "symbols": ["set_grid"],
          "postprocess": $first
        },
        {
          "name": "set",
          "symbols": ["set_debug"],
          "postprocess": $first
        },
        {
          "name": "set",
          "symbols": ["set_vname"],
          "postprocess": $first
        },
        {
          "name": "set_grid",
          "symbols": [
            {
              "literal": "set"
            },
            "__",
            {
              "literal": "grid"
            },
            "__",
            {
              "literal": "to"
            },
            "__",
            "gridsize",
            "_",
            "stop"
          ],
          "postprocess": $set_grid
        },
        {
          "name": "set_debug",
          "symbols": [
            {
              "literal": "set"
            },
            "__",
            {
              "literal": "debug"
            },
            "__",
            {
              "literal": "to"
            },
            "__",
            {
              type: "boolean"
            },
            "_",
            "stop"
          ],
          "postprocess": $set_debug
        },
        {
          "name": "clasz$ebnf$1",
          "symbols": [/[a-z_]/]
        },
        {
          "name": "clasz$ebnf$1",
          "symbols": ["clasz$ebnf$1",
        /[a-z_]/],
          "postprocess": function(d) {
            return d[0].concat([d[1]]);
          }
        },
        {
          "name": "clasz",
          "symbols": [
            {
              "literal": "."
            },
            "clasz$ebnf$1"
          ],
          "postprocess": $clasz
        },
        {
          "name": "stop",
          "symbols": [
            {
              type: "semicolon"
            }
          ],
          "postprocess": $first
        },
        {
          "name": "gridsize",
          "symbols": ["cellkey"],
          "postprocess": $first
        },
        {
          "name": "id",
          "symbols": [
            {
              type: "id"
            }
          ],
          "postprocess": $id
        },
        {
          "name": "select",
          "symbols": ["select_fields"],
          "postprocess": $first
        },
        {
          "name": "select_fields",
          "symbols": [
            {
              "literal": "select"
            },
            "__",
            {
              "literal": "fields"
            },
            "__",
            "selectors",
            "_",
            "stop"
          ],
          "postprocess": $select_fields
        },
        {
          "name": "selectors$ebnf$1",
          "symbols": ["selector_comma"]
        },
        {
          "name": "selectors$ebnf$1",
          "symbols": ["selectors$ebnf$1",
        "selector_comma"],
          "postprocess": function(d) {
            return d[0].concat([d[1]]);
          }
        },
        {
          "name": "selectors",
          "symbols": ["selectors$ebnf$1",
        "selector"],
          "postprocess": $flatten
        },
        {
          "name": "selectors",
          "symbols": ["selector"],
          "postprocess": $flatten
        },
        {
          "name": "selector_comma",
          "symbols": [
            "selector",
            "_",
            {
              type: "comma"
            },
            "_"
          ],
          "postprocess": $first
        },
        {
          "name": "selector",
          "symbols": ["abstract_selector"],
          "postprocess": $first
        },
        {
          "name": "selector",
          "symbols": ["cell_selector"],
          "postprocess": $first
        },
        {
          "name": "abstract_selector",
          "symbols": ["id"],
          "postprocess": $first
        },
        {
          "name": "cell_selector",
          "symbols": ["cellkey"],
          "postprocess": $first
        },
        {
          "name": "cell_selector",
          "symbols": ["rangekey"],
          "postprocess": $first
        },
        {
          "name": "cell_selector",
          "symbols": [
            {
              type: "star"
            }
          ],
          "postprocess": $first
        },
        {
          "name": "cellkey$subexpression$1",
          "symbols": [
            {
              type: "colletters"
            }
          ]
        },
        {
          "name": "cellkey$subexpression$1",
          "symbols": [
            {
              "literal": "*"
            }
          ]
        },
        {
          "name": "cellkey$subexpression$2",
          "symbols": [
            {
              type: "rowdigits"
            }
          ]
        },
        {
          "name": "cellkey$subexpression$2",
          "symbols": [
            {
              "literal": "*"
            }
          ]
        },
        {
          "name": "cellkey",
          "symbols": ["cellkey$subexpression$1",
        "cellkey$subexpression$2"],
          "postprocess": $cellkey
        },
        {
          "name": "rangekey",
          "symbols": [
            "cellkey",
            {
              type: "upto"
            },
            "cellkey"
          ],
          "postprocess": $rangekey
        },
        {
          "name": "__$ebnf$1",
          "symbols": [
            {
              "literal": " "
            }
          ]
        },
        {
          "name": "__$ebnf$1",
          "symbols": [
            "__$ebnf$1",
            {
              "literal": " "
            }
          ],
          "postprocess": function(d) {
            return d[0].concat([d[1]]);
          }
        },
        {
          "name": "__",
          "symbols": ["__$ebnf$1"],
          "postprocess": Σ('LWS')
        },
        {
          "name": "_$ebnf$1",
          "symbols": []
        },
        {
          "name": "_$ebnf$1",
          "symbols": [
            "_$ebnf$1",
            {
              "literal": " "
            }
          ],
          "postprocess": function(d) {
            return d[0].concat([d[1]]);
          }
        },
        {
          "name": "_",
          "symbols": ["_$ebnf$1"],
          "postprocess": Σ('LWS')
        }
      ],
      ParserStart: "phrase"
    };
    if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
      return module.exports = grammar;
    } else {
      return window.grammar = grammar;
    }
  })();

}).call(this);
