// Generated by CoffeeScript 2.3.1
(function() {
  // Generated automatically by nearley, version 2.15.1
  // http://github.com/Hardmath123/nearley
  (function() {
    /*======================================================================================================*/
    /* ====================================================================================================
    nearleyc sqy.ne -o sqy.coffee && coffee -c sqy.coffee && nearley-test -q -i 'create field;' sqy.js
    nearley-railroad sqy.ne -o sqy.html
    nearley-unparse -n 10 sqy.js

    create layout #mylayout;
    set grid to G5;
    set debug to false;
    create field at A1;
    create field at A1..B2;
    create field #myfield at A1..B2;
    select fields #myfield:                       set top border to 'thin, blue';
    select fields #myfield, #thatone, .h, A1..B2: set top border to 'thin, blue';
    select fields .caption:                       set horizontal alignment to left;

    set col[umn]  width[s]  of * to 10;
    set row       height[s] of * to 10;

    cheat!; # a temporary allowance

     * in layout #mylayout, create field at A1;
     * in layout #mylayout, create field at A1..B2;
     * in layout #mylayout, create field at A1, at B2, #anotherfield at C3..D5;
     * in layout #mylayout, create field #myfield at A1..B2;
     * select layout #mylayout, then create: field  #myfield at A1, field at B1, field #another at C3;
     * select layout #mylayout, then create  field: #myfield at A1,       at B1,       #another at C3;
     * create layout: #this, #that;
     * create: layout #this, layout #that;
     * create layout #mylayout, then: create field  #caption.h at A1..D1, create field .text at: A2, B2, C2, D2;
     * create layout #mylayout, then create: field  #caption.h at A1..D1,        field .text at: A2, B2, C2, D2;
     * create layout #mylayout, then create  field: #caption.h at A1..D1,              .text at: A2, B2, C2, D2;

     */
    /*======================================================================================================*/
    var $assignment, $cellkey, $clasz, $create_layout, $create_named_field, $create_unnamed_field, $filter, $filter_flatten, $first, $first_value, $flatten, $id, $ignore, $last, $only_one, $rangekey, $select_fields, $set_ctx_alignment, $set_ctx_border, $set_debug, $set_default_gaps, $set_field_gaps, $set_grid, $set_lane_sizes, $set_sel_alignment, $set_sel_border, $set_unit_lengths, CND, _create_field, alert, badge, debug, echo, enumerate, filter, filtered, flatten, get_loc, grammar, help, id, info, join, jr, lexer, log, rpr, show, urge, warn, whisper, Σ;
    id = function(d) {
      return d[0];
    };
    'use strict';
    
    //###########################################################################################################
    CND = require('cnd');
    rpr = CND.rpr;
    badge = 'SQY/GRAMMAR';
    log = CND.get_logger('plain', badge);
    info = CND.get_logger('info', badge);
    whisper = CND.get_logger('whisper', badge);
    alert = CND.get_logger('alert', badge);
    debug = CND.get_logger('debug', badge);
    warn = CND.get_logger('warn', badge);
    help = CND.get_logger('help', badge);
    urge = CND.get_logger('urge', badge);
    echo = CND.echo.bind(CND);
    ({lexer} = require('./sqy-lexer'));
    
    //-----------------------------------------------------------------------------------------------------------
    log = function(...P) {
      return console.log(...P);
    };
    jr = JSON.stringify;
    
    //-----------------------------------------------------------------------------------------------------------
    flatten = function(d, n = 1) {
      if (n < 1) {
        return d;
      }
      return (n === 1 ? d : flatten(d, n - 1)).reduce((function(a, b) {
        return a.concat(b);
      }), []);
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $flatten = function(d, n = 1) {
      return flatten(d, n);
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $filter = function(d) {
      return d.filter(function(x) {
        return x !== null;
      });
    };
    
    //-----------------------------------------------------------------------------------------------------------
    filter = function*(d) {
      var i, len, x;
      for (i = 0, len = d.length; i < len; i++) {
        x = d[i];
        if (x === null) {
          continue;
        }
        if (x === Symbol.for('LWS')) {
          continue;
        }
        if (x === Symbol.for('STOP')) {
          continue;
        }
        if (x.type === 'semicolon') {
          continue;
        }
        yield x;
      }
    };
    
    //-----------------------------------------------------------------------------------------------------------
    filtered = function(d) {
      return [...(filter(d))];
    };
    
    //-----------------------------------------------------------------------------------------------------------
    enumerate = function*(iterator) {
      var idx, results, x;
      idx = 0;
      results = [];
      for (x of iterator) {
        results.push((yield [x, idx++]));
      }
      return results;
    };
    
    // #-----------------------------------------------------------------------------------------------------------
    // show = ( ref, d ) ->
    //   for token, idx in d
    //     log ( CND.grey ref ), ( CND.white idx ), ( CND.yellow jr token )
    //   return null

    //-----------------------------------------------------------------------------------------------------------
    show = function(d, level = 0) {
      var i, indentation, len, x;
      indentation = '  '.repeat(level);
      for (i = 0, len = d.length; i < len; i++) {
        x = d[i];
        if (x === null) {
          continue;
        }
        if (CND.isa_list(x)) {
          show(x, level + 1);
          continue;
        }
        switch (x.type) {
          case x.value:
            info(indentation, CND.red(jr(x.type)));
            break;
          case 'id':
            info(indentation, CND.lime(x.id));
            break;
          default:
            info(indentation, x.type, rpr(x.value));
        }
      }
      return null;
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $filter_flatten = function(d) {
      return filtered(flatten(d, 2));
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $only_one = function(d) {
      if (d.length !== 1) {
        throw new Error(`µ44909 detected ambiguous grammar ${rpr(d)}`);
      }
      return d[0];
    };
    
    //-----------------------------------------------------------------------------------------------------------
    Σ = function(key) {
      return function() {
        return Symbol.for(key);
      };
    };
    $ignore = function() {
      return null;
    };
    join = function(x, joiner = '') {
      return x.join(joiner);
    };
    get_loc = function(token) {
      return `${token.line}#${token.col}`;
    };
    $first = function(x) {
      return x[0];
    };
    $first_value = function(type) {
      return function(d) {
        return {
          type,
          value: d[0].value
        };
      };
    };
    $last = function(x) {
      return x[x.length - 1];
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $clasz = function(d) {
      var type;
      type = 'clasz';
      id = d[0].value;
      return {type, id};
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $id = function(d) {
      var type;
      type = 'id';
      id = d[0].value;
      return {type, id};
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $cellkey = function(d) {
      var type, value;
      type = 'cellkey';
      value = d[0].value;
      return {type, value};
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $rangekey = function(d) {
      var UPTO, first, second, type;
      // debug '$rangekey', d
      type = 'rangekey';
      [first, UPTO, second] = d;
      return {type, first, second};
    };
    
    //-----------------------------------------------------------------------------------------------------------
    _create_field = function(first, selector, id) {
      var loc, ref, type;
      loc = get_loc(first);
      type = 'create_field';
      // selector  = { type: 'star', } if selector.type is 'star'
      id = (ref = id != null ? id.id : void 0) != null ? ref : null;
      return {type, id, selector, loc};
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $create_named_field = function(d) {
      var AT, CREATE, FIELD, selector;
      [CREATE, FIELD, id, AT, selector] = filtered(d);
      return _create_field(CREATE, selector, id);
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $create_unnamed_field = function(d) {
      var AT, CREATE, FIELD, selector;
      [CREATE, FIELD, AT, selector] = filtered(d);
      return _create_field(CREATE, selector, null);
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $create_layout = function(d) {
      var CREATE, LAYOUT, loc, type;
      [CREATE, LAYOUT, id] = filtered(d);
      loc = get_loc(CREATE);
      type = 'create_layout';
      id = id.id;
      return {type, id, loc};
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $set_grid = function(d) {
      var GRID, SET, TO, cellkey, loc, size, type;
      [SET, GRID, TO, cellkey] = filtered(d);
      loc = get_loc(SET);
      type = 'set_grid';
      size = cellkey;
      return {type, size, loc};
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $set_ctx_border = function(d) {
      var BORDER, SET, TO, edge, edges, loc, style, type;
      [SET, edges, BORDER, TO, style] = filtered(d);
      loc = get_loc(SET);
      type = 'set_ctx_border';
      style = style.value;
      edges = (function() {
        var i, len, results;
        results = [];
        for (i = 0, len = edges.length; i < len; i++) {
          edge = edges[i];
          results.push(edge.value);
        }
        return results;
      })();
      return {type, edges, style, loc};
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $set_sel_border = function(d) {
      var BORDER, OF, SET, TO, edge, edges, loc, selectors, style, type;
      [SET, edges, BORDER, OF, selectors, TO, style] = filtered(d);
      loc = get_loc(SET);
      type = 'set_sel_border';
      style = style.value;
      edges = (function() {
        var i, len, results;
        results = [];
        for (i = 0, len = edges.length; i < len; i++) {
          edge = edges[i];
          results.push(edge.value);
        }
        return results;
      })();
      return {type, edges, selectors, style, loc};
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $assignment = function(d) {
      var SET, TO, loc, rhs, type, value, vname;
      [SET, vname, TO, value] = filtered(d);
      type = (function() {
        switch (value.type) {
          case 'sq_string':
          case 'dq_string':
            return 'text';
          case 'float':
          case 'integer':
            return 'number';
          default:
            return value.type;
        }
      })();
      rhs = {
        type,
        value: value.value
      };
      loc = get_loc(SET);
      type = 'assignment';
      id = vname.value;
      return {type, id, rhs, loc};
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $set_debug = function(d) {
      var DEBUG, SET, TO, loc, toggle, type, value;
      [SET, DEBUG, TO, toggle] = filtered(d);
      loc = get_loc(SET);
      type = 'set_debug';
      value = toggle.value;
      return {type, value, loc};
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $select_fields = function(d) {
      var FIELDS, SELECT, loc, selectors, type;
      [SELECT, FIELDS, selectors] = filtered(d);
      loc = get_loc(SELECT);
      type = 'select_fields';
      return {type, selectors, loc};
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $set_ctx_alignment = function(d) {
      var ALIGN, SET, TO, align, alignment, direction, loc, type;
      // debug 'set_ctx_alignment'
      // show d
      [SET, ALIGN, TO, alignment] = filtered(d);
      loc = get_loc(SET);
      direction = ALIGN.type === 'halign' ? 'horizontal' : 'vertical';
      type = 'set_ctx_alignment';
      align = alignment.value;
      return {type, direction, align, loc};
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $set_sel_alignment = function(d) {
      var ALIGN, OF, SET, TO, align, alignment, direction, loc, selectors, type;
      // debug 'set_sel_alignment'
      // show d
      [SET, ALIGN, OF, selectors, TO, alignment] = filtered(d);
      loc = get_loc(SET);
      direction = ALIGN.type === 'halign' ? 'horizontal' : 'vertical';
      type = 'set_sel_alignment';
      align = alignment.value;
      return {type, selectors, direction, align, loc};
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $set_unit_lengths = function(d) {
      var SET, TO, UNIT, loc, quantity, type, unit, value;
      [SET, UNIT, TO, quantity] = filtered(d);
      if (CND.isa_list(quantity)) {
        [value, unit] = quantity;
      } else {
        [value, unit] = [1, quantity];
      }
      type = 'set_unit_lengths';
      value = CND.isa_number(value) ? value : value.value;
      unit = unit.value;
      loc = get_loc(SET);
      return {type, value, unit};
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $set_lane_sizes = function(d) {
      var SET, TO, direction, lane, loc, type, value;
      // debug 'set_sel_alignment'
      // debug filtered d
      // show d
      [SET, lane, direction, TO, value] = filtered(d);
      type = 'set_lane_sizes';
      loc = get_loc(SET);
      lane = lane.value;
      if (lane === 'column') {
        lane = 'col';
      }
      direction = direction.value;
      if (direction === 'widths') {
        direction = 'width';
      }
      if (direction === 'heights') {
        direction = 'height';
      }
      value = value.value;
      return {type, lane, direction, value};
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $set_default_gaps = function(d) {
      var DEFAULT, GAPS, SET, TO, feature, type, value;
      [SET, DEFAULT, feature, GAPS, TO, value] = filtered(d);
      type = 'set_default_gaps';
      feature = feature.value;
      value = value.value;
      return {type, feature, value};
    };
    
    //-----------------------------------------------------------------------------------------------------------
    $set_field_gaps = function(d) {
      var GAPS, OF, SET, TO, edge, edges, feature, selectors, type, value;
      // debug 'set_field_gaps'
      // debug filtered d
      // show d
      [SET, edges, feature, GAPS, OF, selectors, TO, value] = filtered(d);
      type = 'set_field_gaps';
      feature = feature.value;
      value = value.value;
      edges = (function() {
        var i, len, results;
        results = [];
        for (i = 0, len = edges.length; i < len; i++) {
          edge = edges[i];
          results.push(edge.value);
        }
        return results;
      })();
      return {type, edges, feature, selectors, value};
    };
    grammar = {
      Lexer: lexer,
      ParserRules: [
        {
          "name": "source",
          "symbols": ["_",
        "phrase",
        "source"],
          "postprocess": $filter_flatten
        },
        {
          "name": "source",
          "symbols": ["_",
        "phrase"],
          "postprocess": $last
        },
        {
          "name": "source",
          "symbols": ["_",
        "comment"],
          "postprocess": $filter_flatten
        },
        {
          "name": "comment",
          "symbols": [
            "_",
            {
              type: "comment"
            }
          ],
          "postprocess": $ignore
        },
        {
          "name": "phrase",
          "symbols": ["create"],
          "postprocess": $only_one
        },
        {
          "name": "phrase",
          "symbols": ["set"],
          "postprocess": $only_one
        },
        {
          "name": "phrase",
          "symbols": ["cheat"],
          "postprocess": $last
        },
        {
          "name": "create",
          "symbols": ["create_field"],
          "postprocess": $first
        },
        {
          "name": "create",
          "symbols": ["create_layout"],
          "postprocess": $first
        },
        {
          "name": "create_field",
          "symbols": ["create_named_field"],
          "postprocess": $first
        },
        {
          "name": "create_field",
          "symbols": ["create_unnamed_field"],
          "postprocess": $first
        },
        {
          "name": "create_named_field",
          "symbols": [
            {
              "literal": "create"
            },
            "__",
            {
              "literal": "field"
            },
            "__",
            "id",
            "__",
            {
              "literal": "at"
            },
            "__",
            "cell_selector",
            "s"
          ],
          "postprocess": $create_named_field
        },
        {
          "name": "create_unnamed_field",
          "symbols": [
            {
              "literal": "create"
            },
            "__",
            {
              "literal": "field"
            },
            "__",
            {
              "literal": "at"
            },
            "__",
            "cell_selector",
            "s"
          ],
          "postprocess": $create_unnamed_field
        },
        {
          "name": "create_layout",
          "symbols": ["create_named_layout"],
          "postprocess": $first
        },
        {
          "name": "create_named_layout",
          "symbols": [
            {
              "literal": "create"
            },
            "__",
            {
              "literal": "layout"
            },
            "__",
            "id",
            "s"
          ],
          "postprocess": $create_layout
        },
        {
          "name": "set",
          "symbols": ["set_grid"],
          "postprocess": $first
        },
        {
          "name": "set",
          "symbols": ["set_debug"],
          "postprocess": $first
        },
        {
          "name": "set",
          "symbols": ["set_unit_lengths"],
          "postprocess": $first
        },
        {
          "name": "set",
          "symbols": ["set_col_widths"],
          "postprocess": $first
        },
        {
          "name": "set",
          "symbols": ["set_row_heights"],
          "postprocess": $first
        },
        {
          "name": "set",
          "symbols": ["assignment"],
          "postprocess": $first
        },
        {
          "name": "set",
          "symbols": ["set_sel_border"],
          "postprocess": $first
        },
        {
          "name": "set",
          "symbols": ["set_sel_alignment"],
          "postprocess": $first
        },
        {
          "name": "set",
          "symbols": ["set_default_gaps"],
          "postprocess": $first
        },
        {
          "name": "set",
          "symbols": ["set_field_gaps"],
          "postprocess": $first
        },
        {
          "name": "set_grid",
          "symbols": [
            {
              "literal": "set"
            },
            "__",
            {
              "literal": "grid"
            },
            "__",
            {
              "literal": "to"
            },
            "__",
            "gridsize",
            "s"
          ],
          "postprocess": $set_grid
        },
        {
          "name": "set_debug",
          "symbols": [
            {
              "literal": "set"
            },
            "__",
            {
              "literal": "debug"
            },
            "__",
            {
              "literal": "to"
            },
            "__",
            {
              type: "boolean"
            },
            "s"
          ],
          "postprocess": $set_debug
        },
        {
          "name": "set_unit_lengths",
          "symbols": [
            {
              "literal": "set"
            },
            "__",
            {
              "literal": "unit"
            },
            "__",
            {
              "literal": "to"
            },
            "__",
            "unit",
            "s"
          ],
          "postprocess": $set_unit_lengths
        },
        {
          "name": "set_col_widths",
          "symbols": [
            {
              "literal": "set"
            },
            "__",
            "column",
            "__",
            "width_s",
            "__",
            {
              "literal": "to"
            },
            "__",
            "number",
            "s"
          ],
          "postprocess": $set_lane_sizes
        },
        {
          "name": "set_row_heights",
          "symbols": [
            {
              "literal": "set"
            },
            "__",
            {
              "literal": "row"
            },
            "__",
            "height_s",
            "__",
            {
              "literal": "to"
            },
            "__",
            "number",
            "s"
          ],
          "postprocess": $set_lane_sizes
        },
        {
          "name": "set_sel_border",
          "symbols": [
            {
              "literal": "set"
            },
            "__",
            "edges",
            "__",
            "border_s",
            "__",
            {
              "literal": "of"
            },
            "__",
            "selectors",
            "__",
            {
              "literal": "to"
            },
            "__",
            "style",
            "s"
          ],
          "postprocess": $set_sel_border
        },
        {
          "name": "set_sel_alignment",
          "symbols": [
            {
              "literal": "set"
            },
            "__",
            "halign",
            "__",
            {
              "literal": "of"
            },
            "__",
            "selectors",
            "__",
            {
              "literal": "to"
            },
            "__",
            "halignment",
            "s"
          ],
          "postprocess": $set_sel_alignment
        },
        {
          "name": "set_sel_alignment",
          "symbols": [
            {
              "literal": "set"
            },
            "__",
            "valign",
            "__",
            {
              "literal": "of"
            },
            "__",
            "selectors",
            "__",
            {
              "literal": "to"
            },
            "__",
            "valignment",
            "s"
          ],
          "postprocess": $set_sel_alignment
        },
        {
          "name": "set_default_gaps",
          "symbols": [
            {
              "literal": "set"
            },
            "__",
            {
              "literal": "default"
            },
            "__",
            "feature",
            "__",
            "gap_s",
            "__",
            {
              "literal": "to"
            },
            "__",
            "number",
            "s"
          ],
          "postprocess": $set_default_gaps
        },
        {
          "name": "set_field_gaps",
          "symbols": [
            {
              "literal": "set"
            },
            "__",
            "edges",
            "__",
            "feature",
            "__",
            "gap_s",
            "__",
            {
              "literal": "of"
            },
            "__",
            "selectors",
            "__",
            {
              "literal": "to"
            },
            "__",
            "number",
            "s"
          ],
          "postprocess": $set_field_gaps
        },
        {
          "name": "assignment",
          "symbols": [
            {
              "literal": "set"
            },
            "__",
            {
              type: "vname"
            },
            "__",
            {
              "literal": "to"
            },
            "__",
            "value",
            "s"
          ],
          "postprocess": $assignment
        },
        {
          "name": "cheat",
          "symbols": [
            {
              type: "cheat"
            },
            "s"
          ],
          "postprocess": function() {
            return {
              type: 'cheat'
            };
          }
        },
        {
          "name": "feature",
          "symbols": [
            {
              "literal": "border"
            }
          ],
          "postprocess": $first
        },
        {
          "name": "feature",
          "symbols": [
            {
              "literal": "text"
            }
          ],
          "postprocess": $first
        },
        {
          "name": "feature",
          "symbols": [
            {
              "literal": "background"
            }
          ],
          "postprocess": $first
        },
        {
          "name": "unit",
          "symbols": [
            {
              type: "name"
            }
          ],
          "postprocess": $first
        },
        {
          "name": "unit",
          "symbols": [
            "number",
            {
              type: "name"
            }
          ],
          "postprocess": $flatten
        },
        {
          "name": "value",
          "symbols": ["string"],
          "postprocess": $first
        },
        {
          "name": "value",
          "symbols": ["number"],
          "postprocess": $first
        },
        {
          "name": "value",
          "symbols": [
            {
              type: "boolean"
            }
          ],
          "postprocess": $first
        },
        {
          "name": "string",
          "symbols": [
            {
              type: "dq_string"
            }
          ],
          "postprocess": $first
        },
        {
          "name": "string",
          "symbols": [
            {
              type: "sq_string"
            }
          ],
          "postprocess": $first
        },
        {
          "name": "number",
          "symbols": [
            {
              type: "integer"
            }
          ],
          "postprocess": $first
        },
        {
          "name": "number",
          "symbols": [
            {
              type: "float"
            }
          ],
          "postprocess": $first
        },
        {
          "name": "style",
          "symbols": ["string"],
          "postprocess": $first
        },
        {
          "name": "halign",
          "symbols": [
            {
              type: "halign"
            }
          ],
          "postprocess": $first
        },
        {
          "name": "valign",
          "symbols": [
            {
              type: "valign"
            }
          ],
          "postprocess": $first
        },
        {
          "name": "border_s",
          "symbols": [
            {
              "literal": "border"
            }
          ],
          "postprocess": $first
        },
        {
          "name": "border_s",
          "symbols": [
            {
              "literal": "borders"
            }
          ],
          "postprocess": $first
        },
        {
          "name": "gap_s",
          "symbols": [
            {
              "literal": "gap"
            }
          ],
          "postprocess": $first
        },
        {
          "name": "gap_s",
          "symbols": [
            {
              "literal": "gaps"
            }
          ],
          "postprocess": $first
        },
        {
          "name": "edges$ebnf$1",
          "symbols": ["edge_comma"]
        },
        {
          "name": "edges$ebnf$1",
          "symbols": ["edges$ebnf$1",
        "edge_comma"],
          "postprocess": function(d) {
            return d[0].concat([d[1]]);
          }
        },
        {
          "name": "edges",
          "symbols": ["edges$ebnf$1",
        "edge"],
          "postprocess": $flatten
        },
        {
          "name": "edges",
          "symbols": ["edge"]
        },
        {
          "name": "edge_comma",
          "symbols": [
            "edge",
            "_",
            {
              type: "comma"
            },
            "_"
          ],
          "postprocess": $first
        },
        {
          "name": "edge",
          "symbols": [
            {
              "literal": "top"
            }
          ],
          "postprocess": $first_value('edge')
        },
        {
          "name": "edge",
          "symbols": [
            {
              "literal": "left"
            }
          ],
          "postprocess": $first_value('edge')
        },
        {
          "name": "column",
          "symbols": [
            {
              "literal": "col"
            }
          ],
          "postprocess": $first_value('lane')
        },
        {
          "name": "column",
          "symbols": [
            {
              "literal": "column"
            }
          ],
          "postprocess": $first_value('lane')
        },
        {
          "name": "width_s",
          "symbols": [
            {
              "literal": "width"
            }
          ],
          "postprocess": $first_value('direction')
        },
        {
          "name": "width_s",
          "symbols": [
            {
              "literal": "widths"
            }
          ],
          "postprocess": $first_value('direction')
        },
        {
          "name": "height_s",
          "symbols": [
            {
              "literal": "height"
            }
          ],
          "postprocess": $first_value('direction')
        },
        {
          "name": "height_s",
          "symbols": [
            {
              "literal": "heights"
            }
          ],
          "postprocess": $first_value('direction')
        },
        {
          "name": "edge",
          "symbols": [
            {
              "literal": "bottom"
            }
          ],
          "postprocess": $first_value('edge')
        },
        {
          "name": "edge",
          "symbols": [
            {
              "literal": "right"
            }
          ],
          "postprocess": $first_value('edge')
        },
        {
          "name": "edge",
          "symbols": [
            {
              "literal": "all"
            }
          ],
          "postprocess": $first_value('edge')
        },
        {
          "name": "halignment",
          "symbols": [
            {
              "literal": "left"
            }
          ],
          "postprocess": $first_value('halignment')
        },
        {
          "name": "halignment",
          "symbols": [
            {
              "literal": "right"
            }
          ],
          "postprocess": $first_value('halignment')
        },
        {
          "name": "halignment",
          "symbols": [
            {
              "literal": "center"
            }
          ],
          "postprocess": $first_value('halignment')
        },
        {
          "name": "halignment",
          "symbols": [
            {
              "literal": "justified"
            }
          ],
          "postprocess": $first_value('halignment')
        },
        {
          "name": "valignment",
          "symbols": [
            {
              "literal": "top"
            }
          ],
          "postprocess": $first_value('valignment')
        },
        {
          "name": "valignment",
          "symbols": [
            {
              "literal": "bottom"
            }
          ],
          "postprocess": $first_value('valignment')
        },
        {
          "name": "valignment",
          "symbols": [
            {
              "literal": "center"
            }
          ],
          "postprocess": $first_value('valignment')
        },
        {
          "name": "selectors$ebnf$1",
          "symbols": ["selector_comma"]
        },
        {
          "name": "selectors$ebnf$1",
          "symbols": ["selectors$ebnf$1",
        "selector_comma"],
          "postprocess": function(d) {
            return d[0].concat([d[1]]);
          }
        },
        {
          "name": "selectors",
          "symbols": ["selectors$ebnf$1",
        "selector"],
          "postprocess": $flatten
        },
        {
          "name": "selectors",
          "symbols": ["selector"],
          "postprocess": $flatten
        },
        {
          "name": "selector_comma",
          "symbols": [
            "selector",
            "_",
            {
              type: "comma"
            },
            "_"
          ],
          "postprocess": $first
        },
        {
          "name": "selector",
          "symbols": ["abstract_selector"],
          "postprocess": $first
        },
        {
          "name": "selector",
          "symbols": ["cell_selector"],
          "postprocess": $first
        },
        {
          "name": "abstract_selector",
          "symbols": ["id"],
          "postprocess": $first
        },
        {
          "name": "cell_selector",
          "symbols": ["cellkey"],
          "postprocess": $first
        },
        {
          "name": "cell_selector",
          "symbols": ["rangekey"],
          "postprocess": $first
        },
        {
          "name": "rangekey",
          "symbols": [
            "cellkey",
            {
              type: "upto"
            },
            "cellkey"
          ],
          "postprocess": $rangekey
        },
        {
          "name": "cellkey",
          "symbols": [
            {
              type: "cellkey"
            }
          ],
          "postprocess": $cellkey
        },
        {
          "name": "clasz$ebnf$1",
          "symbols": [/[a-z_]/]
        },
        {
          "name": "clasz$ebnf$1",
          "symbols": ["clasz$ebnf$1",
        /[a-z_]/],
          "postprocess": function(d) {
            return d[0].concat([d[1]]);
          }
        },
        {
          "name": "clasz",
          "symbols": [
            {
              "literal": "."
            },
            "clasz$ebnf$1"
          ],
          "postprocess": $clasz
        },
        {
          "name": "s",
          "symbols": [
            {
              type: "semicolon"
            }
          ],
          "postprocess": $first
        },
        {
          "name": "gridsize",
          "symbols": ["cellkey"],
          "postprocess": $first
        },
        {
          "name": "id",
          "symbols": [
            {
              type: "id"
            }
          ],
          "postprocess": $id
        },
        {
          "name": "__$ebnf$1",
          "symbols": [
            {
              type: "ws"
            }
          ]
        },
        {
          "name": "__$ebnf$1",
          "symbols": [
            "__$ebnf$1",
            {
              type: "ws"
            }
          ],
          "postprocess": function(d) {
            return d[0].concat([d[1]]);
          }
        },
        {
          "name": "__",
          "symbols": ["__$ebnf$1"],
          "postprocess": $ignore
        },
        {
          "name": "_$ebnf$1",
          "symbols": []
        },
        {
          "name": "_$ebnf$1",
          "symbols": [
            "_$ebnf$1",
            {
              type: "ws"
            }
          ],
          "postprocess": function(d) {
            return d[0].concat([d[1]]);
          }
        },
        {
          "name": "_",
          "symbols": ["_$ebnf$1"],
          "postprocess": $ignore
        }
      ],
      ParserStart: "source"
    };
    if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
      return module.exports = grammar;
    } else {
      return window.grammar = grammar;
    }
  })();

}).call(this);
