{"name": "create", "symbols": ["create_field"], "postprocess": $first},
{"name": "create", "symbols": ["create_layout"], "postprocess": $first},
{"name": "create_field", "symbols": ["create_named_field"], "postprocess": $first},
{"name": "create_field", "symbols": ["create_unnamed_field"], "postprocess": $first},
xxxxxxxxxxxxxxxxx (lexer.has("id") ? {type: "id"} : id), "__", {"literal":"at"}, "__", "selector", "_", "STOP"], "postprocess": $create_field},
{"name": "create_unnamed_field", "symbols": [{"literal":"create"}, "__", "FIELD", "__", {"literal":"at"}, "__", "selector", "_", "STOP"], "postprocess": $create_field},
{"name": "create_layout", "symbols": ["create_named_layout"], "postprocess": $first},
xxxxxxxxxxxxxxxxx (lexer.has("id") ? {type: "id"} : id), "_", "STOP"], "postprocess": $create_layout},
{"name": "set", "symbols": ["set_grid"], "postprocess": $first},
